In [31]:
import numpy as np   #### -> numpy는 무조건 인덱스 접근.

my_array = np.arange(100000)
my_list = list(range(100000))

In [14]:
%timeit my_list2 = [1* 2 for i in my_list]
%timeit my_array2 = my_array * 2

1.57 ms ± 105 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
46.1 μs ± 731 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [17]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0],
]
data = np.array(a)
print(data) #### -> 데이터의 형을 맞춰주는 함수 np.array()

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [25]:
# 0차원: 스칼라(scala), 1차원: 백터(vector), 2차원: 행렬(matrix), 3차원 이상: 텐서(tenser)
# 배열에 좀 더 특화되어있다.
print(data * 10 )
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [32]:
print(data.shape)  ## ex) 가장 바깥에 2개의 배열, 그 안에 3개의 배열
print(data.dtype)  ## float데이터가 64비트로 이루어져 있다.

(2, 3)
float64


## ndarray 생성하기

In [37]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [43]:
arr2 = np.array([[1.1, 1.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 1.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [45]:
print(arr1.ndim)  ## -> 몇차원인가를 알려줌.
print(arr2.ndim)

1
2


In [46]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [56]:
print(np.zeros(10))
# print([0] * 10)
print(np.zeros(    [5, 5]    )     )
print(np.empty((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [59]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [71]:
arr1 = np.array([1, 2, 3], dtype=np.float64)  
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [72]:
arr1 = np.array([1, 2, 3])   ## -> 명시적으로 형변환 할때 사용.
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [79]:
arr2 = np.array([1.1, 2.2, 3.3])  ### -> 소수점 뒤에 자리는 버림. float도 int로 바꿀 수 있음. int도 float로 가능(astype 사용)
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3]
int64


## 산술 연산

In [85]:
arr = np.array([[4, 5, 6], [1, 2, 3]])
print(arr)
print(arr * arr)
print(arr + arr)
print(1/arr)
print(arr ** 3)  ## -> 같은 위치의 데이터 가능.

[[4 5 6]
 [1 2 3]]
[[16 25 36]
 [ 1  4  9]]
[[ 8 10 12]
 [ 2  4  6]]
[[0.25       0.2        0.16666667]
 [1.         0.5        0.33333333]]
[[ 64 125 216]
 [  1   8  27]]


In [92]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)   ## -> 전체의 합을 비교하는 것이 아니라, 각각의 위치에 딸려있는 숫자를 비교한다. 그리고 True or False로 출력한다.
print(arr == 3)

[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [1 2 3]]
[[ True  True  True]
 [False False False]]
[[False False False]
 [False False  True]]


## 색인과 슬라이싱

In [94]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [96]:
print(arr[5])
print(arr[2:5])

5
[2 3 4]


In [98]:
arr[2:5] = 10
print(arr)

[ 0  1 10 10 10  5  6  7  8  9]


In [99]:
arr[4:10] = 9
print(arr)

[ 0  1 10 10  9  9  9  9  9  9]


In [106]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)   ###->원본 그대로 출력되어야함.

[1, 2, 3, 4, 5]


In [110]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [117]:
print(arr[1][1])
print(arr[1, 1])

5
5


In [122]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [11, 22, 33], [44, 55, 66]]])
print(arr3d[2][1][0])
print(arr3d[2, 1, 0])

11
11


In [124]:
arr3d[:1 ]  ##->0번째 데이터만 출력.

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [127]:
arr3d[0, 1:, 2:]  # -> 0은 인덱스 접근이기 때문에, 한 차원을 줄여주게 된다.

array([[6],
       [9]])

In [129]:
arr3d[:1, 1:, 2:]  # -> :1은 인덱스 접근이 아니어서, 차원을 줄이지 않는다

array([[[6],
        [9]]])

In [132]:
arr3d[0, 1:, 2:] = 9999 ## ->6과 9에 있던 데이터들이 모두 9999로 변경.
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  10   11   12]
  [  13   14   15]
  [  16   17   18]]

 [[  19   20   21]
  [  11   22   33]
  [  44   55   66]]]


## 불리언 값으로 선택

In [139]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 90],['math', 80],['eng', 70],['eng', 50]])

In [145]:
names == 'kim'

array([False,  True, False,  True])

In [148]:
# data[[True, False, True, False]]   -> 내가 원하고 특정 조건에 맞는 데이터를 고를 때 사용.
data[names == 'hong']

array([['math', '90'],
       ['eng', '70']], dtype='<U21')

In [151]:
print(data[names == 'hong' , 1])
print(data[names == 'hong', :1])

['90' '70']
[['math']
 ['eng']]


In [158]:
print(names != 'hong')  ##-> 'hong'이 아닌가요? 를 묻는 표현 !=

[False  True False  True]


In [159]:
print(~(names == 'hong'))  ## -> 'hong'이 아닌가요? 를 묻는 또 다른 표현 ~

[False  True False  True]


In [162]:
cond = names == 'kim'  ##-> 앞으로는 cond라는 변수에 넣어 사용할거임.
data[cond]

array([['math', '80'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인(fancy indexing)

In [169]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i  ##-> 같은 줄에 있는 거에 같은 데이터가 출력됨.
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [171]:
arr[[4, 3, 0, 5]]  #-> index에 list를 넣으면 내가 원해서 지정하는대로 만들 수 있음.

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [172]:
arr[[-3, -2, -1]]

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [189]:
arr = np.arange(32).reshape(8, 4)
# print(arr)

In [197]:
arr[[1, 5], [2, 3]]

array([ 6, 23])

In [198]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])

## 배열 전치

In [201]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [203]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [212]:
##->행렬의 내적, 곱  - 직접적으로 쓸일은 없지만 알아두기.....
print(arr @ arr.T) 
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [213]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)

[[ 0.46205239  0.11909678 -0.68935546]
 [ 1.04177699  0.2102432  -0.72282223]
 [ 2.05467776 -1.50516275 -0.37341173]]


In [221]:
arr1 = np.sqrt(samples)  ## -> nan(not a number) : 숫자가 음수일때, 데이터를 빈칸으로 만들어버림. 결측치.
print(arr1)

[[0.67974436 0.34510401        nan]
 [1.02067477 0.45852285        nan]
 [1.43341472        nan        nan]]


C:\Users\1-01\AppData\Local\Temp\ipykernel_15672\1561689514.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)  ## -> nan(not a number) : 숫자가 음수일때, 데이터를 빈칸으로 만들어버림. 결측치.


In [222]:
arr2 = np.abs(samples)   ## -> abs: 절댓값으로 바꿈.
print(arr2)

[[0.46205239 0.11909678 0.68935546]
 [1.04177699 0.2102432  0.72282223]
 [2.05467776 1.50516275 0.37341173]]


In [223]:
np.isnan(arr1)

array([[False, False,  True],
       [False, False,  True],
       [False,  True,  True]])